name: unit-test
on:
    push:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: python installation
              uses: actions/setup-python@v4 # apt-get python 3.12.10
              with:
                python-version: '3.12'
            - name: install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: run tests
              run: |
                pytest --doctest-modules --junitxml=junit/test-results.xml


